### ISSUE TITLE
Can't find ~/.bitcoin folder

### ISSUE THREAD

**Issue by FugueWeb** [evapeak/bitcoind#1]
Hello Evapeak,

Thank you for this tutorial. I have followed it word for word, but despite several attempts there is no .bitcoin folder in my home directory. After I run 'sudo make install' and I go to move the block folder to the mounted second drive, the /.bitcoin folder simply does not exist. Can you please provide any insight on how to troubleshoot? Thanks!

**Comment by bitcoinbrisbane** [comment]
Thanks for reviewing the steps.

Off memory, you actually have to run bitciond one time

It will then complain about not having a bitcoin.conf file.  After that, the ~./bitcoin/blocks folder should be there.

**Comment by FugueWeb** [comment]
Yes, that worked. Thanks! I made the edit to the readme file.

**Comment by bitcoinbrisbane** [comment]
Great!

On 16 Dec 2015, at 9:43 AM, Fugue Web <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes, that worked. Thanks! I made the edit to the readme file.

##

**Comment by FugueWeb** [comment]
Now I'm having some trouble with the second disk in /media/data and the symbolic link. Can you tell me what is the point of this step? Why can't the blocks just stay in ~/.bitcoin/blocks and avoid mounting this other disk (which is resulting in errors for me when I run `bitcoind`)?

**Comment by bitcoinbrisbane** [comment]
I wrote the instructions originally for a Raspberry Pi style deployment, where the OS drive is very small.  So I used an external memory card for the blocks.  So if your OS disk is large enough (120GB+) then that will be fine.

Also, you have to remember if the main disk gets full, then sometimes the OS won’t boot or work, because there is no swap space.  So can be good to use a 2nd disk.

Latter builds of Bitcoin Core / Bitcoind also have a Block path setting in bitcoin.conf so you don’t have to use symbolic links.

Note:  Im not a Ubuntu expert.  These where just my steps i worked out so i thought id share so people like yourselves could get it up and running.
